### ISSUE TITLE
Segfault when given invalid file ( Adding Comma at end of line )

### ISSUE THREAD

**Issue by ImOphen** [mohammedhrima/compiler#2]
<img width="1140" alt="image" src="https://github.com/mohammedhrima/compiler/assets/43254081/a3348cf6-20ed-42e0-a882-4de038cfca00">
<img width="399" alt="image" src="https://github.com/mohammedhrima/compiler/assets/43254081/ed080f3b-5529-48f9-8476-6c139dbb5e55">

Hello, Big fan of the project and big ups for the huge work, i played with it a little bit, and found this segfault, works on any line of the file ( even empty ones )

**Comment by mohammedhrima** [comment]
Thank you so much for your effort, and for your time,
I believe it's fixed now, you can check, if there is any issue don't hesitate 
I will keep doing my best
